### PR TITLE
TEIID-4154: remove dynamic vdb terminology for quickstrat and quickst…

### PR DESCRIPTION
**Pull request by kylinsoong**
remove dynamic vdb terminology for quickstrat and quickstart docs

### CODE REVIEW

**Comment by vhalbert** [comment]
Need to also increment the version in the pom's for this change to related to teiid 9.x.

**Comment by kylinsoong** [comment]
@vhalbert, increase the version to 4.0.0 or just increase the minor version like 3.1.0?

**Comment by vhalbert** [comment]
I would say increase to 4.0, as I would consider these breaking changes that align it with Teiid 9, and breaks from the Teiid 8 dynamic vdb usage.

Van Halbert

----- Original Message -----

**Comment by shawkins** [comment]
Thanks Kylin

**Pull request merged**
